
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import database.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ebene
 */
public class customerCheckIn extends javax.swing.JFrame {
        //Dfifing instance
        
    /**
     * Creates new form customerCheckIn
     */
    public customerCheckIn() {
        initComponents();
        checkin.setEditable(false);
        pric.setEditable(false);
        //
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();
        checkin.setText(format.format(cal.getTime()));
    }
    
    String bedType;
    String roomType;
    String price;
    String roomNumber;
    /**
     * This method performs actions on room
     */
    public void roomDetails(){
       //Removing anyItem in the roomNumber;
        roomNum.removeAllItems();
        //Get the data form GUI
        pric.setText("");
        bedType = (String) bedSel.getSelectedItem();
        roomType = (String) rType.getSelectedItem();
        //roomNumber = (String) roomNum.getSelectedItem();
        //price = pric.getText();
        //Retriving information from data baser 
        try {
            ResultSet rs = Selector.getData("select * from room where bed='"+bedType+"' and roomType='"+roomType+"' and status='Not booked'");
            while(rs.next()){
                //System.out.println(rs.getString(1));
                roomNum.addItem(rs.getString(1));
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bedSel = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        rType = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pric = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        roomNum = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(65, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setText("CUSTOMER CHECK IN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 69, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 125, -1, -1));

        nam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 150, 258, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Moblie No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 196, -1, -1));

        tel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 224, 258, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 261, -1, -1));

        nation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 286, 258, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 321, -1, -1));

        sex.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 346, 258, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 380, -1, -1));

        em.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 405, 258, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("ID Proof");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 125, -1, -1));

        id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 153, 178, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 196, -1, -1));

        addr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 224, 178, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Check IN DATE(TODAY)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 261, -1, -1));

        checkin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 286, 178, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        bedSel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bedSel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        bedSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedSelActionPerformed(evt);
            }
        });
        getContentPane().add(bedSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 130, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, -1, -1));

        rType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));
        rType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTypeActionPerformed(evt);
            }
        });
        getContentPane().add(rType, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 130, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, -1, -1));

        pric.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(pric, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 99, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton1.setText("Allote Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 119, -1));

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, -1, -1));

        roomNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        roomNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumActionPerformed(evt);
            }
        });
        getContentPane().add(roomNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new homePage().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new managerRoom().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bedSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedSelActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_bedSelActionPerformed

    private void rTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTypeActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_rTypeActionPerformed

    private void roomNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumActionPerformed
         // TODO add your handling code here:
        String price = this.pric.getText();
        roomNumber = (String)roomNum.getSelectedItem();
        try {
            ResultSet rs = Selector.getData("select * from room where roomNum='"+roomNumber+"'");
            while(rs.next()){
                pric.setText(rs.getString(4));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_roomNumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Collecting user information;
        int userId = 1;
        String customenName = nam.getText();
        String telephone = tel.getText();
        String nationality = nation.getText();
        String gender = (String) sex.getSelectedItem();
        String customerEmail = em.getText();
        String idProof = id.getText();
        String address = addr.getText();
        String checkIn = checkin.getText();
        String bed = (String) bedSel.getSelectedItem();
        String roomType = (String) rType.getSelectedItem();
        String roomNumber = (String) roomNum.getSelectedItem();
        String price = pric.getText();
        String query;
        try {
            //Checking if id is already exist else we incresses
            ResultSet rs = Selector.getData("select max(id) from customer");
            while(rs.next()){
                userId = rs.getInt(1);//we call id
            }
            rs.close();
            //we increase id
            //inf
            if(!price.equals("")){
                userId = userId + 1;
                query = "update room set status='booked' where roomNum='"+roomNumber+"'";
                InsertUpdateDelete.setData(query, "");
                //Updating checking
                query = "insert into customer(id,name,moblieNum,nationality,gender,email,idProof,address,checkIn,bed,roomType,roomNum,pricePeyDay) values("+userId+",'"+customenName+"','"+telephone+"','"+nationality+"','"+gender+"','"+customerEmail+"','"+idProof+"','"+address+"','"+checkIn+"','"+bed+"','"+roomType+"','"+roomNumber+"','"+price+"')";
                InsertUpdateDelete.setData(query, "CHECK IN succesfully");
                //Clear
                setVisible(false);
                new customerCheckIn().setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JComboBox<String> bedSel;
    private javax.swing.JTextField checkin;
    private javax.swing.JTextField em;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField nation;
    private javax.swing.JTextField pric;
    private javax.swing.JComboBox<String> rType;
    private javax.swing.JComboBox<String> roomNum;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
